#ifndef WENDA_REDUCERS_REDUCERS_COMMON_H_INCLUDED
#define WENDA_REDUCERS_REDUCERS_COMMON_H_INCLUDED

#define WENDA_REDUCERS_NAMESPACE wenda::reducers
#define WENDA_REDUCERS_NAMESPACE_BEGIN namespace wenda { namespace reducers {
#define WENDA_REDUCERS_NAMESPACE_END } }

#endif // WENDA_REDUCERS_REDUCERS_COMMON_H_INCLUDED